config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  root 'reviews#index'

  resources :users, only: %i[index show update] do
    member do
      get :following, :followers
      get :boards
    end
    get :likes, on: :collection
  end

  resources :books do
    collection do
      get 'search'
    end
  end

  namespace :reviews do
    resources :searches, only: :index
    resources :action_plans, only: %i[show update]
  end

  resources :reviews, only: %i[create destroy show update] do
    resources :comments, only: %i[create destroy]
    resource :likes, only: %i[create destroy]
  end

  namespace :boards do
    resources :searches, only: :index
  end

  resources :boards, only: %i[index show create update destroy] do
    resources :board_comments, only: %i[create destroy]
  end

  resources :relationships, only: %i[create destroy]
  resources :messages, only: %i[create destroy]
  resources :rooms, only: %i[index create show]
  resources :notifications, only: %i[index destroy]
end

app/models/board_comment.rb
class BoardComment < ApplicationRecord
  belongs_to :user
  has_many :notifications, dependent: :destroy
  has_one_attached :image

  validates :text, presence: true, length: { maximum: 200 }

  scope :recent, -> { order(created_at: :desc) }

  def create_notification_comment(current_user, board_comment_id, board_id)
    temp_ids = BoardComment.select(:user_id).where(board_id: board_id).where.not(user_id: current_user.id).distinct

    temp_ids.each do |temp_id|
      save_notification_comment(current_user, temp_id['user_id'], board_comment_id, board_id)
    end

    visited_id = Board.find(board_id).user_id
    save_notification_comment(current_user, visited_id, board_comment_id, board_id) if temp_ids.blank?
  end

  def save_notification_comment(current_user, visited_id, board_comment_id, board_id)
    notification = current_user.active_notifications.new(
      visited_id: visited_id,
      board_id: board_id,
      board_comment_id: board_comment_id,
      action: 'board_comment'
    )
    notification.checked = true if notification.visitor_id == notification.visited_id
    notification.save if notification.valid?
  end
end

app/controllers/board_comments_controller.rb
class BoardCommentsController < ApplicationController
  def create
    @board_comment = BoardComment.create(board_comment_params)
    if @board_comment.save
      board = Board.find(params[:board_id])
      @board_comment.create_notification_comment(
        current_user,
        @board_comment.id,
        board.id
      )
      redirect_to request.referer
    end
  end

  def destroy
    board_comment = BoardComment.find(params[:board_id])
    redirect_to request.referer if board_comment.destroy
  end

  private

  def board_comment_params
    params.permit(:text, :image).merge(
      user_id: current_user.id,
      board_id: params[:board_id]
    )
  end
end

app/views/board_comments/_board_comment-list.html.erb
<div class="container-fluid review-show">
  <div class="row">
    <div class="col-md-3">
    </div>

    <div class="col-md-7">
      <div class="review-show_content mb-5">

        <div class="review-show_review">
          <div class="board-show_comment_user_icon mb-3">
            <%= render partial: "shared/user-image", locals: {attr: comment} %>
            <p class="board-show-user_name text-center"><%= comment.user.username %></p>
          </div>

          <%# -----コメント内容----- %>
          <div id="js-board_comment" class="review-show_txt text-center">
            <p id="js-board_comment-<%= comment.id %>" class="board_comment" data-id="<%= comment.id %>"><%= safe_join(comment.text.split("\n"), tag(:br)) %></p>
            <%= image_tag comment.image.variant(resize: '500x500'), id:"js-board_comment-img_#{comment.id}", class:"board_comment-img", data:{id:"#{comment.id}", image:"#{url_for(comment.image)}"} if comment.image.attached? %>
          </div>
        </div>

      </div>
    </div>

    <div class="col-md-2 review-show_icons">

      <%# -----コメント削除アイコン----- %>
      <% if user_signed_in? && current_user.id == comment.user_id %>
        <div class="review-show_del review-index_del">
          <%= link_to board_board_comment_path(comment.id), method: :delete, class: "review-show_del_btn", data: { confirm: '本当に削除しますか' } do %>
            <i class="far fa-trash-alt fa-2x"></i>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/board_comments/_new-board_comment-modal.erb
<div class="modal fade" id="board_commentModal" tabindex="-1" role="dialog" aria-labelledby="board_commentModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <span class="modal-header-title">コメントを作成する</span>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_with url: board_board_comments_path(@board.id) do |f| %>

          <div class="row my-3">
            <%= f.label :text, "内容", class:"col-lg-3" %>
            <%= f.text_area :text, id:"js-board-comment", class:"col form-control mx-2 js-board-comment", rows:"8", placeholder:"コメントを記入しましょう", required: true %>
            <span id="js-board-comment_count" class="js-board-comment_count"></span>
            <span>/200</span>
          </div>

          <div class="row my-3">
            <%= f.label :image, "画像", class:"col-lg-3" %>
          </div>
          <hr>

          <div>
            <% if @board_comment.image.attached? %>
              <%= image_tag @board.image, class:"col mx-2 edit-board_img" %>
            <% else %>
              <%= image_tag "no-image.png", class:"col mx-2 edit-board_img" %>
            <% end %>
            <%= f.file_field :image, class:"edit-board_img_input" %>
          </div>

          <div class="row">
            <div class="col-9"></div>
            <div class="col-3">
              <div class="col-9 d-flex">
                <%= f.submit "返信する", class:"board-submit" %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>