config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  root 'reviews#index'

  resources :users, only: %i[index show update] do
    member do
      get :following, :followers
      get :boards
    end
    get :likes, on: :collection
  end

  resources :books do
    collection do
      get 'search'
    end
  end

  namespace :reviews do
    resources :searches, only: :index
    resources :action_plans, only: %i[show update]
  end

  resources :reviews, only: %i[create destroy show update] do
    resources :comments, only: %i[create destroy]
    resource :likes, only: %i[create destroy]
  end

  namespace :boards do
    resources :searches, only: :index
  end

  resources :boards, only: %i[index show create update destroy] do
    resources :board_comments, only: %i[create destroy]
  end

  resources :relationships, only: %i[create destroy]
  resources :messages, only: %i[create destroy]
  resources :rooms, only: %i[index create show]
  resources :notifications, only: %i[index destroy]
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }

  belongs_to :visitor, class_name: 'User'
  belongs_to :visited, class_name: 'User'
  belongs_to :board_comment, optional: true
  belongs_to :board,         optional: true
  belongs_to :comment,       optional: true
  belongs_to :review,        optional: true

  validates :visitor_id, presence: true
  validates :visited_id, presence: true
  ACTION_VALUES = %w[like follow comment board_comment]
  validates :action, presence: true, inclusion: { in: ACTION_VALUES }
  validates :checked, inclusion: { in: [true, false] }
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @notifications = current_user.passive_notifications.includes(:visitor, :visited)
    @notifications.where(checked: false).each do |notification|
      notification.update(checked: true)
    end
  end

  def destroy
    @notifications = current_user.passive_notifications.destroy_all
    redirect_to notifications_path
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def notification_form(notification)
    @visitor = notification.visitor
    @comment = nil
    @visitor_comment = notification.comment_id

    case notification.action
    when 'follow'
      tag.a(@visitor.username, href: user_path(@visitor)) + 'があなたをフォローしました'
    when 'like'
      tag.a(@visitor.username,
            href: user_path(@visitor)) + 'が' + tag.a('あなたの投稿', href: review_path(notification.review_id)) + 'にいいねしました'
    when 'comment'
      @comment = Comment.find_by(id: @visitor_comment)
      @comment_text = @comment.text
      tag.a(@visitor.username,
            href: user_path(@visitor)) + 'が' + tag.a('あなたの投稿', href: review_path(notification.review_id)) + 'にコメントしました'
    when 'board_comment'
      @board_comment = BoardComment.find_by(id: @visitor_board_comment)
      tag.a(@visitor.username,
            href: user_path(@visitor)) + 'が' + tag.a('スレッド', href: board_path(notification.board_id)) + 'にコメントしました'
    end
  end

  def unchecked_notifications
    @notifications = current_user.passive_notifications.where(checked: false)
  end
end

app/views/notifications/_alert.html.erb
<% if unchecked_notifications.any? %>
  <i class="fas fa-circle alert-circle"></i>
<% end %>

app/views/notifications/_notification.html.erb
<div class="notification_list-wrapper">
  <ul>
    <li class="notification_list-item">
      <% if notification.visitor.image.attached? %>
        <%= link_to user_path(notification.visitor) do %>
          <%= image_tag notification.visitor.image, class: "relationship_list-avatar-img" %>
          <%= notification_form(notification) %>
        <% end %>
      <% else %>
        <%= link_to user_path(notification.visitor) do %>
          <%= image_tag "default-user.png", class: "relationship_list-avatar-img" %>
          <%= notification_form(notification) %>
        <% end %>
      <% end %>
      <span class="text-muted"><%= "(#{time_ago_in_words(notification.created_at)}前)" %>
      </li>
    </ul>
</div>

app/views/notifications/index.html.erb
<h1 class="notification-title text-center">通知</h1>
<%= link_to "すべて削除", notification_path(@notifications), method: :delete, class: "fas fa-trash notification_del mb-4" %>
<% notifications = @notifications.where.not(visitor_id: current_user.id) %>
<% if notifications.exists? %>
  <div class="notification_list">
    <%= render @notifications %>
  </div>
<% else %>
  <p class="text-center">通知はありません</p>
<% end %>