config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  root 'reviews#index'

  resources :users, only: %i[index show update] do
    member do
      get :following, :followers
      get :boards
    end
    get :likes, on: :collection
  end

  resources :books do
    collection do
      get 'search'
    end
  end

  namespace :reviews do
    resources :searches, only: :index
    resources :action_plans, only: %i[show update]
  end

  resources :reviews, only: %i[create destroy show update] do
    resources :comments, only: %i[create destroy]
    resource :likes, only: %i[create destroy]
  end

  namespace :boards do
    resources :searches, only: :index
  end

  resources :boards, only: %i[index show create update destroy] do
    resources :board_comments, only: %i[create destroy]
  end

  resources :relationships, only: %i[create destroy]
  resources :messages, only: %i[create destroy]
  resources :rooms, only: %i[index create show]
  resources :notifications, only: %i[index destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:twitter]

  has_many :sns_credentials, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :user_books, dependent: :destroy
  has_many :books, through: :user_books,
                   dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :active_relationships,  class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :rooms, through: :entries, source: :room
  has_many :active_notifications,  class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  has_one_attached :image

  validates :username, presence: true,
                       length: { maximum: 20 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    uniqueness: true,
                    format: {
                      with: VALID_EMAIL_REGEX,
                      message: 'のフォーマットが不適切です'
                    }
  # validates :password, presence: true,
  #                      length: {
  #                       minimum: 6,
  #                       maximum: 128,
  #                      }
  validates :profile, length: { maximum: 160 }

  def self.find_for_oauth(auth)
    sns_credentials = SnsCredential.where(uid: auth.uid, provider: auth.provider).first

    if sns_credentials.present?
      sns_credentials.user
    elsif auth.provider == 'twitter'
      User.create_user_with_twitter(auth)
    else
      User.where(email: auth.info.email).first
    end
  end

  def self.create_user_with_twitter(auth)
    user = User.new(
      email: User.dummy_email(auth),
      username: auth.info.nickname,
      password: Devise.friendly_token[0, 20]
    )
    sns_credentials = SnsCredential.new(
      uid: auth.uid,
      provider: auth.provider,
      user: user
    )

    return user if user.save && sns_credentials.save
  end

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end

  def liked_by?(review_id)
    likes.where(review_id: review_id).exists?
  end

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  # -----フォロー通知-----
  def create_notification_follow(current_user)
    temp = Notification.where(['visitor_id = ? and visited_id = ? and action = ?',
                               current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  def self.search(search)
    return User.all unless search

    User.where('username LIKE(?)', "%#{search}%")
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.username = 'ゲストユーザー'
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
    callback_for(:twitter)
  end

  private

  def callback_for(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.present? && provider == 'twitter'
      session[:oauth_token] = request.env['omniauth.auth']['credentials']['token']
      session[:oauth_token_secret] = request.env['omniauth.auth']['credentials']['secret']
      sign_in_and_redirect @user, event: :authentication
    elsif @user.present?
      sign_in_and_redirect @user, event: :authentication
    else
      redirect_to new_user_session_path
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :ensure_normal_user, only: %i[update destroy]

  def ensure_normal_user
    redirect_to root_path, alert: 'ゲストユーザーの更新・削除はできません' if resource.email == 'guest@example.com'
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: %i[show update following followers boards]

  def index
    @users = User.all.search(params[:keyword]).page(params[:page]).per(10)
  end

  def show
    @books = user_book_status(0)
    @reading = user_book_status(1)
    @will_read = user_book_status(2)

    @like_list = Kaminari.paginate_array(Like.find(Like.where(user_id: @user.id).ids)).page(params[:page]).per(20)

    @review = Review.new

    if user_signed_in?
      @currentUserEntry = Entry.where(user_id: current_user.id)
      @userEntry = Entry.where(user_id: @user.id)
      unless @user.id == current_user.id
        @currentUserEntry.each do |cu|
          @userEntry.each do |u|
            if cu.room_id == u.room_id
              @isRoom = true
              @roomId = cu.room_id
            end
          end
        end
        unless @isRoom # まだルームが作られていなければ
          @room = Room.new
          @entry = Entry.new
        end
      end
    end

    review_categories = @user.reviews.group(:category).count
    @review_it         = review_categories['it']
    @review_management = review_categories['management']
    @review_economy    = review_categories['economy']
    @review_finance    = review_categories['finance']
    @review_thinking   = review_categories['thinking']
    @review_motivation = review_categories['motivation']
    @review_novel      = review_categories['novel']
    @review_etc        = review_categories['etc']
  end

  def update
    @user.update(user_params)
    redirect_to user_path(current_user)
  end

  def following
    @title = 'Following'
    @users = @user.following
    render 'show_relationship'
  end

  def followers
    @title = 'Followers'
    @users = @user.followers
    render 'show_relationship'
  end

  def boards
    @created_boards = Board.where(user_id: @user).order('created_at desc').page(params[:page]).per(10)
    @participated_boards = Board.find(BoardComment.where(user_id: @user).order('created_at desc').page(params[:page]).per(10).pluck(:board_id))
    render 'show_board'
  end

  private

  def user_params
    params.require(:user).permit(:username, :image, :profile)
  end

  def find_user
    @user = User.find(params[:id])
  end

  def user_book_status(status)
    Book.joins(:user_books).where(user_books: {
                                    user_id: params[:id],
                                    status: status
                                  }).order(created_at: 'DESC').page(params[:page]).per(20)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit-profile-modal.html.erb
<div class="modal fade" id="edit-profile-modal" tabindex="-1" role="dialog"  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">プロフィールを編集</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <%= form_with(model: user,
                      url: user_path,
                      method: :put,
                      local: true) do |f| %>
        <div class="modal-body">

          <%# -----トプ画表示----- %>
          <div class="edit-user_img_container">
            <% if user.image.attached? %>
              <%= image_tag(user.image, class: "edit-user_img") %>
            <% else %>
              <%= image_tag("default-user.png", class: "edit-user_img") %>
            <% end %>

            <%# -----トプ画アップロード----- %>
            <div class="edit-user_upload_img">
              <%= f.label :image, class: "edit-user_img_label" do %>
                <i class="fas fa-camera fa-2x"></i>
              <% end %>
              <%= f.file_field :image, class: "edit-user_img_input" %>
            </div>
          </div>

          <%# -----名前----- %>
          <div class="form-group">
            <%= f.label :name, "名前", class: "edit-user_label" %>
            <%= f.text_field(:username,
                              placeholder: "名前を変更",
                              value: user.username,
                              maxlength: 20,
                              id: "edit-user_name",
                              class: "form-control") %>
            <%# -----文字数カウント----- %>
            <span class="edit-user_count">
              <span id="edit-user_name_count"></span>
              <span>/20</span>
            </span>
          </div>

          <%# -----自己紹介----- %>
          <div class="form-group">
            <%= f.label :profile, "自己紹介",
                        class: "edit-user_label" %>
            <%= f.text_area(:profile,
                            placeholder: "自己紹介を追加",
                            value: user.profile,
                            maxlength: 160,
                            rows: 6,
                            id: "edit-user_text",
                            class: "form-control edit-user_text_area") %>
            <%# -----文字数カウント----- %>
            <span class="edit-user_count">
              <span id="edit-user_text_count"></span>
              <span>/160</span>
            </span>
          </div>
        </div>

        <%# -----保存ボタン----- %>
        <div class="modal-footer">
          <%= f.submit("保存", class: "edit-user_submit") %>
        </div>

      <% end %>

    </div>
  </div>
</div>

app/views/users/_user.html.erb
<div class="relationship_list-wrapper">
  <ul class="relationship_list-content">
    <li class="d-flex relationship_list-item">
      <%= link_to user do %>
        <% if user.image.present? %>
          <%= image_tag user.image, class: "relationship_list-avatar-img" %>
        <% else %>
          <%= image_tag asset_path("default-user.png"), class: "relationship_list-avatar-img" %>
        <% end %>
      <% end %>
      <div class="my-auto list-item-content relationship_list-status">
        <p><%= link_to user.username, user %><p>
        <p><%= user.profile %></p>
      </div>
    </li>
  </ul>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="mt-4">
  <h4 class="notification-title text-center">ユーザー一覧</h4>
  <%= form_with url: users_path, method: :get, class:"user-search_form", local: true do |f| %>
    <%= f.text_field :keyword, placeholder: "ユーザーを検索する", class: "user-search_input" %>
    <%= f.button type: "submit", class: "user-search_btn" do %>
      <i class="fas fa-search"></i>
    <% end %>
  <% end %>
    <% if @users.present? %>
      <%= render @users %>
      <%= paginate @users %>
    <% else %>
      <p class="text-center mt-5">該当のユーザーはいません</p>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container-fluid review-show">
  <div class="row">

    <div class="col-md-3">
      <%= render partial: "shared/user-profile", locals: { user: @user } %>
    </div>

    <div class="col-md-7">

      <div class="user-show_tabs">
        <input id="tab1" type="radio" name="a" checked>
        <label class="user-show_tabs_label" for="tab1">読んだ本</label>
        <input id="tab2" type="radio" name="a">
        <label class="user-show_tabs_label" for="tab2">読んでる本</label>
        <input id="tab3" type="radio" name="a">
        <label class="user-show_tabs_label" for="tab3">読みたい本</label>
        <input id="tab4" type="radio" name="a">
        <label class="user-show_tabs_label" for="tab4">ブックマーク</label>

        <%# ----------読んだ本---------- %>
        <div class="user-show_tab_content" id="tab1_content">
          <div class="tab_content_description">
            <div class="card-deck user-show_books">
              <div class="card-body d-flex flex-wrap">
                <% @books.each do |book| %>
                  <div class="col-md-3 border-0">
                    <div class="text-center">
                      <%= link_to review_path(book.reviews.ids) do %>
                        <%= image_tag(book[:image_url], class: "user-show_book_img") %>
                      <% end %>
                      <div class="card-body">
                        <div class="card-title">
                          <%= book[:title] %>
                        </div>
                        <div class="card-text">
                          <%= book[:authors] %>
                        </div>
                      </div>
                    </div>
                  </div>
                <% end %>
                <%= paginate @books %>
              </div>
            </div>
          </div>
        </div>

        <%# ----------読んでる本---------- %>
        <div class="user-show_tab_content" id="tab2_content">
          <div class="tab_content_description">
            <div class="card-deck user-show_books">
              <div class="card-body d-flex flex-wrap">
                <% @reading.each_with_index do |reading, i| %>
                  <%# <div class="col-md-3 border-0"> %>
                  <div class="col-md-3 border-0 book-content" id="book-item_<%= reading.id %>">
                    <div class="text-center">
                      <%# -----ここからボタン----- %>
                      <% if user_signed_in? && @user.id == current_user.id %>
                        <div class="add-book-cover">
                          <div class="book-menu">
                            <label class="add-book" id="add-book" for="add-book-btn<%= reading.id %>">本を登録する</label>
                            <input type="checkbox" id="add-book-btn<%= reading.id %>" class="accordion">
                            <style>
                              #add-book-btn<%=reading.id%> {
                                display: none;
                              }
                              #add-book-btn<%=reading.id%>:checked ~ #book-btn li {
                                height: 54px;
                                opacity: 1;
                              }
                            </style>
                            <ul id="book-btn">

                              <div class="read-book" data-toggle="modal" data-target="#post-review-modal" data-title="<%= reading[:title] %>" data-authors="<%= reading[:authors] %>" data-image="<%= reading[:image_url] %>" data-uid="<%= reading[:uid] %>" >
                                <li>読んだ</li>
                              </div>

                              <div class="destroy-book" id="destroy-book_<%= reading.id %>" data-id="<%= reading.id %>">
                                <li>削除</li>
                              </div>

                            </ul>
                          </div>
                        </div>
                      <% end %>
                      <%# -----ここまでボタン----- %>
                      <%= image_tag(reading[:image_url], class: "user-show_book_img") %>
                      <div class="card-body">
                        <div class="card-title">
                          <%= reading[:title] %>
                        </div>
                        <div class="card-text">
                          <%= reading[:authors] %>
                        </div>
                      </div>
                    </div>
                  </div>
                <% end %>
                <%= paginate @reading %>
              </div>
            </div>
          </div>
        </div>

        <%# ----------読みたい本---------- %>
        <div class="user-show_tab_content" id="tab3_content">
          <div class="tab_content_description">
            <div class="card-deck user-show_books">
              <div class="card-body d-flex flex-wrap">
                <% @will_read.each_with_index do |will_read, i| %>
                  <div class="col-md-3 border-0">
                    <div class="text-center">
                      <% if user_signed_in? && @user.id == current_user.id %>
                        <div class="add-book-cover">
                          <div class="book-menu">
                            <label class="add-book" id="add-book" for="add-book-btn<%= will_read.id %>">本を登録する</label>
                            <input type="checkbox" id="add-book-btn<%= will_read.id %>" class="accordion">
                            <style>
                              #add-book-btn<%=will_read.id%> {
                                display: none;
                              }
                              #add-book-btn<%=will_read.id%>:checked ~ #book-btn li {
                                height: 54px;
                                opacity: 1;
                              }
                            </style>
                            <ul id="book-btn">

                              <div class="read-book" data-toggle="modal" data-target="#post-review-modal" data-title="<%= will_read[:title] %>" data-authors="<%= will_read[:authors] %>" data-image="<%= will_read[:image_url] %>" data-uid="<%= will_read[:uid] %>" >
                                <li>読んだ</li>
                              </div>

                              <div class="destroy-book" id="destroy-book_<%= will_read.id %>" data-id="<%= will_read.id%>">
                                <li>削除</li>
                              </div>

                            </ul>
                          </div>
                        </div>
                      <% end %>
                      <%= image_tag(will_read[:image_url], class: "user-show_book_img") %>
                      <div class="card-body">
                        <div class="card-title">
                          <%= will_read[:title] %>
                        </div>
                        <div class="card-text">
                          <%= will_read[:authors] %>
                        </div>
                      </div>
                    </div>
                  </div>
                <% end %>
                <%= paginate @will_read %>
              </div>
            </div>
          </div>
        </div>

        <%# ----------ブックマーク---------- %>
        <div class="user-show_tab_content" id="tab4_content">
          <div class="tab_content_description">
            <div class="card-deck user-show_books">
              <div class="card-body d-flex flex-wrap">
                <% if @like_list.present? %>
                  <% @like_list.each do |like| %>
                    <div class="col-md-3 border-0">
                      <div class="text-center">
                        <%= link_to review_path(like.review.id) do %>
                          <%= image_tag(like.review.book[:image_url], class: "user-show_book_img") %>
                        <% end %>
                        <div class="card-body">
                          <div class="card-title">
                            <%= like.review.book[:title] %>
                          </div>
                          <div class="card-text">
                            <%= like.review.book[:authors] %>
                          </div>
                        </div>
                      </div>
                    </div>
                  <% end %>
                <% end %>
                <%= paginate @like_list %>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

    <div class="col-md-2 mt-3">
      <%# -----グラフ----- %>
      <div class="user-show_category_graph mb-4">
        <canvas id="categoryChart" width="350" height="350"></canvas>
        <script>
        var ctx = document.getElementById("categoryChart").getContext('2d');
        ctx.canvas.height = 350;
        var categoryChart = new Chart(ctx, {
            type: 'doughnut',
            data: {
                labels: ["IT", "経営戦略", "政治・経済・社会", "ファイナンス", "思考法", "自己啓発", "小説", "その他"],
                datasets: [{
                    label: 'ジャンル',
                    data: ["<%= @review_it %>", "<%= @review_management %>", "<%= @review_economy %>", "<%= @review_finance %>", "<%= @review_thinking %>", "<%= @review_motivation %>", "<%= @review_novel %>", "<%= @review_etc %>"],
                    backgroundColor: [
                      '#3333ff', // IT
                      '#0ff15d', // 経営戦略
                      '#f94552', // 政治・経済・社会
                      '#fadd40', // ファイナンス
                      '#f945ac', // 思考法
                      '#0ff1ce', // 自己啓発
                      '#afb5fc', // 小説
                      '#e9e8ea' // その他
                    ],
                }]
            },
            options: {
              maintainAspectRatio: false,
            }
        });
        </script>
      </div>

      <% if user_signed_in? %>
        <% if @user.id == current_user.id %>
          <%= link_to rooms_path, class:"user-show_chat mb-4" do %>
            メッセージ <i class="fas fa-envelope fa-size"></i>
          <% end %>
        <% else %>
          <% if @isRoom == true %>
            <p class="user-show-room">
              <%= link_to room_path(@roomId), class:"btn-lg user-show_chat mb-4" do %>
                チャットへ
              <% end %>
            </p>
          <% else %>
            <%= form_for @room do |f| %>
              <%= fields_for @entry do |e| %>
                <%= e.hidden_field :user_id, value: @user.id %>
              <% end %>
              <%= f.submit "チャットを始める", class:"btn-lg user-show_chat mb-4"%>
            <% end %>
          <% end %>
        <% end %>
      <% end %>

      <%= link_to reviews_action_plan_path(@user), class: "user-show_plans mb-4" do %>
        アクションプラン<i class="fas fa-running fa-size"></i>
      <% end %>

      <%= link_to boards_user_path(@user), class: "user-show_boards" do %>
        スレッド<i class="fas fa-comments fa-size"></i>
      <% end %>

    </div>

  </div>
</div>
<%= render "shared/post-review-modal" %>

app/views/users/show_board.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2"></div>

    <div class="board-show_tabs col-md-8">
      <input id="tab1" type="radio" name="a" checked>
      <label class="board-show_label board-show_created_tab" for="tab1">作成したスレッド</label>

      <input id="tab2" type="radio" name="a">
      <label class="board-show_label" for="tab2">返信したスレッド</label>

      <div class="board-show_tab_content" id="tab1_content">
        <h4 class="board-show_title">作成したスレッド</h4>
        <%= render partial: "shared/board", collection: @created_boards, as: "board" %>
      </div>

      <div class="board-show_tab_content" id="tab2_content">
        <h4 class="board-show_title">返信したスレッド</h4>
        <%= render partial: "shared/board", collection: @participated_boards, as: "board" %>
      </div>
    </div>

    <div class="col-md-2"></div>
  </div>
</div>

app/views/users/show_relationship.html.erb
<div class="container relationship_list">
  <div class="relationship_list-username">
    <%= link_to @user do %>
      <%= @user.username %>
    <% end %>
  </div>

  <%= render "shared/status" %>

  <% if @users.any? %>
    <%= render @users %>
  <% end %>
</div>