config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  root 'reviews#index'

  resources :users, only: %i[index show update] do
    member do
      get :following, :followers
      get :boards
    end
    get :likes, on: :collection
  end

  resources :books do
    collection do
      get 'search'
    end
  end

  namespace :reviews do
    resources :searches, only: :index
    resources :action_plans, only: %i[show update]
  end

  resources :reviews, only: %i[create destroy show update] do
    resources :comments, only: %i[create destroy]
    resource :likes, only: %i[create destroy]
  end

  namespace :boards do
    resources :searches, only: :index
  end

  resources :boards, only: %i[index show create update destroy] do
    resources :board_comments, only: %i[create destroy]
  end

  resources :relationships, only: %i[create destroy]
  resources :messages, only: %i[create destroy]
  resources :rooms, only: %i[index create show]
  resources :notifications, only: %i[index destroy]
end

app/views/shared/_board-index.html.erb
<div class="review-blank"></div>
  <div class="reviews-index container-fluid">
    <div class="row">

      <div class="blank col-md-2">
      </div>

      <div class="review-index col-md-8">

      <div class="boards-form">
        <div class="boards-new d-flex mb-3">
          <i class="fas fa-pen fa-lg mt-2"></i> <h4>作成</h4>
          <% if user_signed_in? %>
            <button type="button" class="boards-new_btn" data-toggle="modal" data-target="#new_boardModal">
              あたらしく作る
            </button>
          <% else %>
            <%= link_to new_user_registration_path, class:"btn" do %>
              あたらしく作る
            <% end %>
          <% end %>
        </div>

        <div class="board-search d-flex">
          <i class="fas fa-search fa-lg mt-2"></i> <h4 class="board-search_label">検索</h4>
          <%= form_with url: boards_searches_path, local: true, method: :get, class: 'board-search_form' do |f| %>
            <%= f.text_field :keyword, placeholder: 'キーワード', class: 'board-search_input' %>
            <%= f.button type: "submit", class: "board-search_btn" do %>
              <i class="fas fa-search"></i>
            <% end %>
          <% end %>
        </div>
      </div>

      <% @boards.each do |board| %>
        <%= render partial: "shared/board", locals: { board: board } %>
      <% end %>

      <%= paginate @boards %>

      </div>

    <div class="ranking-book col-md-2">
    </div>

  </div>
</div>

<%= render "shared/new-board-modal" %>

app/views/shared/_board.html.erb
<div class="container-fulid">
  <div class="timeline card-group card-columns">
    <div class="card review-index_item">
      <div class="review-index_content board-background-img">
        <div class="review-index_head">

          <div class="col review-index_head_user">
            <%# -----トプ画----- %>
            <div class="review-index_user_icon i">
              <%= render partial: "shared/user-image", locals: {attr: board} %>
            </div>
            <%# -----ユーザー名----- %>
            <div class="review-index_user_name">
              <%= board.user.username %>
            </div>
          </div>

          <div class="col review-index_head_img board-background-img">
            <%= image_tag board.image if board.image.attached? %>
          </div>

        </div>

        <%# -----レビュー内容----- %>
        <%= link_to board_path(board.id), class:"review-index_show" do %>
          <div class="review-index_inner_content">
            <%# -----ヒトコト----- %>
            <h2 class="review-index_title">
              <%= board.title %>
            </h2>
            <%# -----感想----- %>
            <div class="review-index_txt">
              <p><%= board.description %></p>
            </div>
          <% end %>

          <div class="board-index_bottom">
            <%# -----削除ボタン----- %>
            <% if user_signed_in? && current_user.id == board.user_id %>
              <div class="board-index_del">
                <%= link_to board_path(board.id), method: :delete, class: "review-index_del_btn", data: { confirm: '本当に削除しますか' } do %>
                  <i class="far fa-trash-alt fa-2x"></i>
                <% end %>
              </div>
            <% else %>
              <div></div>
            <% end %>

            <div class="board-index_type"><%= t("boards.#{board.board_type}") %></div>

            <%# -----コメント数----- %>
            <div class="board-index_comment" id="like_<%= board.id %>">
              <i class="far fa-comment fa-2x"></i> <span class="board-comments-count"><%= board.comments.length %></span>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_comment-list.html.erb
<section class="comment-index_section">

  <div class="comment-index_head">
    <div class="comment-index_head_user">

      <%= link_to user_path(comment.user.id), class: "comment-index_head_user_img" do %>
        <% if comment.user.image.attached? %>
          <%= image_tag comment.user.image %>
        <% else %>
          <%= image_tag "default-user.png" %>
        <% end %>

      <span class="comment-index_head_user_name">
        <%= comment.user.username %>
      </span>

      <% end %>
    </div>

    <div class="comment-index_head_date">
      <time><%= comment.created_at.strftime('%Y-%m-%d %H:%M:%S') %></time>

      <% if user_signed_in? && current_user.id == comment.user_id %>
        <%= link_to review_comment_path(comment.review_id, comment.id), method: :delete, remote: true, class: "comment_destroy", data: { confirm: '本当に削除しますか' } do %>
          <i class="far fa-trash-alt"></i>
        <% end %>
      <% else %>
        <span></span>
      <% end %>

      <div class="comment-index_head_dots">
        <div class="comment-index_head_dots_content">
          <p class="comment-index_head_del is-hidden">削除する</p>
        </div>
      </div>
    </div>

  </div>

  <div class="comment-index_content">
    <p><%= comment.text %></p>
  </div>

</section>

app/views/shared/_datepicker.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-datetimepicker/2.7.1/css/bootstrap-material-datetimepicker.min.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment.min.js"></script>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/locale/ja.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-datetimepicker/2.7.1/js/bootstrap-material-datetimepicker.min.js"></script>
<script>
$(function(){
    $("#date").bootstrapMaterialDatePicker({
      weekStart:0,
      lang:"ja",
      time: false,
      format:"YYYY-MM-DD"
    });
  });
  </script>

app/views/shared/_edit-review-modal.erb
<div class="modal fade" id="edit-review-modal" tabindex="-1" role="dialog"aria-hidden="true">
  <div class="modal-dialog modal-xl modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <span id="post-review-modal-title">レビューを編集する</span>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true"><i class="fas fa-times text-muted"></i></span>
        </button>
      </div>
      <div class="modal-body row" id="modal-book-data">
        <div class="col-sm-3 border-right text-center">
          <%= image_tag('',
                        class: 'modal-review-img',
                        id: 'modal-review-img') %>
        </div>
        <div class="modal-text col-sm-9">

          <%# -----form_with----- %>
          <%= form_with model: @review do |f| %>
            <%= hidden_field_tag "user_book[status]", 0 %>
            <%= hidden_field_tag "book[title]", "", class: "modal-book-title" %>
            <%= hidden_field_tag "book[authors]", "", class: "modal-book-authors" %>
            <%= hidden_field_tag "book[image_url]", "", class: "modal-book-img" %>
            <%= hidden_field_tag "book[uid]", "", class: "modal-book-uid" %>

            <p class="text-center"><span class="red-point">*</span> は必須項目です</p>

            <%# -----読み終わった日----- %>
            <div class="row">
              <p class="col-lg-3 post-review-label my-auto">読み終わった日<span class="red-point">*</span></p>
              <div class="input-group date col-lg-3">
                <%= f.text_field :date, id:"date-input", class:"date result form-control review-date" %>
              </div>
            </div>

            <%# -----ジャンル----- %>
            <div class="row mt-3">
              <p class="col-lg-3 post-review-label my-auto">ジャンル<span class="red-point">*</span></p>
              <div class="col-lg-5 post-review-genre">
                <%= f.select :category, options_for_select(Review.categories.keys.map {|k| [I18n.t("enums.review.category.#{k}"), k]}, selected: @review.category), {include_blank: "選択してください"}, {class: "post-review-genre-select", required: true} %>
              </div>
            </div>

            <%# -----ヒトコト----- %>
            <div class="row mt-3">
              <p class="col-lg-3 post-review-label my-auto">ヒトコト<span class="red-point">*</span></p>
              <%= f.text_field :tegline, id:"review-tegline", class:"review-tegline col form-control mx-2", rows:"8", placeholder:"この本をヒトコトでいうと？", required: true %>
              <span class="review_count col-2">
                <span id="review-tegline_count"></span>
                <span>/25</span>
              </span>
            </div>

            <%# -----感想----- %>
            <div class="row my-3">
              <p class="col-lg-3 post-review-label">感想</p>
              <%= f.text_area :text, class:"review-text col form-control mx-2", id:"review-text", rows:"8" %>
              <span class="review_count col-2">
                <span id="review-text_count"></span>
                <span>/400</span>
              </span>
            </div>

            <%# -----印象に残ったフレーズ----- %>
            <div class="row my-2 phrase-form-area">
              <%= f.fields_for :impressive_phrase, @review.impressive_phrase do |phrase| %>
                <p class="col-lg-3 post-review-label my-auto">印象的なフレーズ</p>
                <div class="js-phrase-form-group col-lg-7 mb-2" data-index="<%= phrase.index %>">
                  <div class="phrase input-group">
                    <%= phrase.text_field :phrase, class:"form-control", id:"phrase-input_#{phrase.index}", placeholder: "印象的なフレーズを記入" %>
                  </div>
                </div>
              <% end %>
            </div>

            <%# -----アクションプラン----- %>
            <div class="row my-2 plan-form-area">
              <%= f.fields_for :action_plan, @review.action_plan do |plan| %>
                <p class="col-lg-3 post-review-label my-auto">アクションプラン<span class="red-point">*</span></p>
                <div class="js-plan-form-group col-lg-7" data-index="<%= plan.index %>">
                  <div class="plan input-group">
                    <%= plan.text_field :plan, class:"form-control", id:"plan-input", placeholder:"アクションプランを記入", required: true %>
                    <%= plan.text_field :deadline, id:"deadline-input", class:"date result form-control review-date", placeholder:"期限", required: true %>
                  </div>
                </div>
                <script>
                  $(function () {
                    $('.date').bootstrapMaterialDatePicker({
                        time: false,
                        lang:"ja",
                    });
                  });
                </script>
              <% end %>
            </div>

            <%# -----星評価機能----- %>
            <div class="row mt-2 mx-2" id="edit-star">
              <p class="col-lg-3 post-review-rating my-auto">評価<span class="red-point">*</span></p>
            </div>
            <script>
              $('#edit-star').raty({
                size: 36,
                starOff: "/assets/star-off.png",
                starOn: "/assets/star-on.png",
                scoreName: "review[rating]"
              });
            </script>

            <%# -----登録するボタン----- %>
            <div class="row">
              <div class="col-8"></div>
              <div class="col-3">
                <div class="col-9 d-flex">
                  <%= f.submit "更新する", class: "review-submit" %>
                </div>
              </div>
            </div>
          <% end %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<header class="header">
  <div class="wrapper header__wrapper">
    <div class="header__left">
      <%= link_to root_path, class:"brand" do %>
        <h1 class="header__title">READER</h1>
      <% end %>
      <div class="search">
        <%= render 'shared/search' %>
      </div>
    </div>
    <div class="header__right">
      <nav class="pc">
        <ul class="nav__wrapper">
          <%# -----ホーム----- %>
          <li class="nav__item">
            <%= link_to root_path do %>
              <i class="fas fa-home header-fa-size"></i>
              <small>ホーム</small>
            <% end %>
          </li>
          <%# -----スレッド----- %>
          <li class="nav__item">
            <%= link_to boards_path do %>
              <i class="fas fa-comments header-fa-size"></i>
              <small>スレッド</small>
            <% end %>
          </li>
          <%# -----ユーザー一覧----- %>
          <li class="nav__item">
            <%= link_to users_path do %>
              <i class="fas fa-users header-fa-size"></i>
              <small>ユーザー一覧</small>
            <% end %>
          </li>
          <% if user_signed_in? %>
            <%# -----アクションプラン----- %>
            <li class="nav__item">
              <%= link_to reviews_action_plan_path(current_user) do %>
                <i class="fas fa-running header-fa-size"></i>
                <small>アクションプラン</small>
              <% end %>
            </li>
            <%# -----通知----- %>
            <li class="nav__item">
              <%= link_to notifications_path do %>
                <%= render "notifications/alert" %>
                <i class="fas fa-bell header-fa-size"></i>
                <small>通知</small>
              <% end %>
            </li>
            <%# -----マイページ----- %>
            <li class="nav__item">
              <%= link_to user_path(current_user) do %>
                <i class="fas fa-user-circle header-fa-size"></i>
                <small>プロフィール</small>
              <% end %>
            </li>
            <%# -----サインアウト----- %>
            <li id="nav__sign_out" class="nav__item">
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fas fa-sign-out-alt header-fa-size"></i>
                <small>ログアウト</small>
              <% end %>
            </li>
          <% else %>
            <li class="nav__item">
              <%= link_to new_user_registration_path do %>
                <i class="fas fa-user-plus header-fa-size"></i>
                <small>新規登録/</br>ログイン</small>
              <% end %>
            </li>
          <% end %>
        </ul>
      </nav>

      <div id="hamburger">
        <div class="icon">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>

      <nav class="sm">
        <ul class="sm_ul">
          <%# -----ホーム----- %>
          <li class="nav__item">
            <%= link_to root_path do %>
              ホーム
            <% end %>
          </li>
          <%# -----スレッド----- %>
          <li class="nav__item">
            <%= link_to boards_path do %>
              スレッド
            <% end %>
          </li>
          <%# -----ユーザー一覧----- %>
          <li class="nav__item">
            <%= link_to users_path do %>
              ユーザー一覧
            <% end %>
          </li>
          <% if user_signed_in? %>
            <%# -----アクションプラン----- %>
            <li class="nav__item">
              <%= link_to reviews_action_plan_path(current_user) do %>
                アクションプラン
              <% end %>
            </li>
            <%# -----通知----- %>
            <li class="nav__item">
              <%= link_to notifications_path do %>
                <%= render "notifications/alert" %>
                通知
              <% end %>
            </li>
            <%# -----マイページ----- %>
            <li class="nav__item">
              <%= link_to user_path(current_user) do %>
                プロフィール
              <% end %>
            </li>
            <%# -----サインアウト----- %>
            <li class="nav__item">
              <%= link_to destroy_user_session_path, method: :delete do %>
                サインアウト
              <% end %>
            </li>
          <% else %>
            <li class="nav__item">
              <%= link_to new_user_registration_path do %>
                新規登録/ログイン
              <% end %>
            </li>
          <% end %>
        </ul>
      </nav>

      <script>
        $('#hamburger').on('click', function(){
          $('.icon').toggleClass('close');
          $('.sm').slideToggle();
        });
      </script>

    </div>
  </div>
</header>

app/views/shared/_new-board-modal.html.erb
<div class="modal fade" id="new_boardModal" tabindex="-1" role="dialog" aria-labelledby="new_boardModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <span class="modal-header-title">スレッドを作成する</span>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="board-modal-body">
        <%= form_with model: @board do |f| %>
          <div class="row mt-3">
            <%= f.label :title, "タイトル", class:"col-lg-3" %>
            <%= f.text_field :title, id:"js-board-title", class:"col form-control mx-2 js-board-title", rows:"8", placeholder:"例）おすすめの本を教えてください", required: true %>
            <span class="review_count col-2">
              <span id="js-board-title_count" class="js-board-title_count"></span>
              <span>/25</span>
            </span>
          </div>

          <div class="row my-3">
            <%= f.label :boards_type, "カテゴリ", class:"col-lg-3" %>
            <div class="col-lg-5">
              <%= f.select :board_type, options_for_select(Board.board_types.keys.map {|k| [I18n.t("enums.board.board_type.#{k}"), k]}, selected: Board.board_types), {include_blank: "選択してください"}, {id:"js-edit-board_type", required: true} %>
            </div>
          </div>

          <div class="row my-3">
            <%= f.label :description, "内容", class:"col-lg-3" %>
            <%= f.text_area :description, id:"js-board-text", class:"col form-control mx-2 js-board-text", rows:"8", placeholder:"なるべくわかりやすく質問をしましょう", required: true %>
            <span class="review_count col-2">
              <span id="js-board-text_count" class="js-board-text_count"></span>
              <span>/200</span>
            </span>
          </div>

          <div class="row my-3">
            <%= f.label :image, "画像", class:"col-lg-3" %>
          </div>
          <hr>
          <div>
            <% if @board.image.attached? %>
              <%= image_tag @board.image, class:"col mx-2 edit-board_img" %>
            <% else %>
              <%= image_tag "no-image.png", class:"col mx-2 edit-board_img" %>
            <% end %>
            <%= f.file_field :image, class:"edit-board_img_input" %>
          </div>

          <div class="row">
            <div class="col-9 board-margin"></div>
            <div class="col-3">
              <div class="col-9 d-flex">
                <%= f.submit "作成する", class:"board-submit btn-primary" %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_review-search.html.erb
<%= form_with(url: reviews_searches_path, local: true, method: :get, class: "review-search_form") do |f| %>
  <%= f.text_field :keyword, placeholder: "投稿を検索する", class: "review-search_input" %>
  <%= f.button type: "submit", class: "review-search_btn" do %>
    <i class="fas fa-search"></i>
  <% end %>
<% end %>

app/views/shared/_review.html.erb
<div class="container-fulid">
  <div class="timeline card-group card-columns">
    <div class="card review-index_item">
      <div class="review-index_content">
        <div class="review-index_head">

          <div class="col review-index_head_user">
            <%# -----トプ画----- %>
            <div class="review-index_user_icon">
              <%= render partial: "shared/user-image", locals: {attr: review} %>
            </div>
            <%# -----ユーザー名----- %>
            <div class="review-index_user_name">
              <%= review.user.username %>
            </div>
          </div>

          <div class="col review-index_head_img">
            <%= link_to book_path(review.book) do %>
              <%= image_tag("#{review.book.image_url}") %>
            <% end %>
          </div>

        </div>

        <%# -----レビュー内容----- %>
        <%= link_to review_path(review.id), class:"review-index_show" do %>
          <div class="review-index_inner_content">
            <%# -----ヒトコト----- %>
            <h2 class="review-index_title">
              <%= review.tegline %>
            </h2>
            <%# -----感想----- %>
            <div class="review-index_text">
              <p><%= review.text %></p>
            </div>
          <% end %>

          <div class="a d-flex">
            <%# -----削除ボタン----- %>
            <% if user_signed_in? && current_user.id == review.user_id %>
              <div class="review-index_del">
                <%= link_to review_path(review.id), method: :delete, class: "review-index_del_btn", data: { confirm: '本当に削除しますか' } do %>
                  <i class="far fa-trash-alt fa-2x"></i>
                <% end %>
              </div>
            <% else %>
              <span></span>
            <% end %>

            <%# -----ブックマーク----- %>
            <div class="review-index_fav" id="like_<%= review.id %>">
              <%= render partial: "likes/like-review", locals: { review: review} %>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_search.html.erb
<%= form_with url: search_books_path, local: true, method: :get, class: 'book-search_container' do |f| %>
  <%= f.text_field :keyword, placeholder: 'タイトル、著者名', class: 'book-search_input' %>
  <%= f.button type: "submit", class: "book-search_btn" do %>
    <i class="fas fa-search fa-lg"></i>
  <% end %>
<% end %>

app/views/shared/_status.html.erb
<% @user ||= current_user %>
<div class="relationship_list-count">
  <%= link_to following_user_path(@user) do %>
    <strong id="following">
      <%= @user.following.count %>
    </strong>
    フォロー
  <% end %>
  <span> | </span>
  <%= link_to followers_user_path(@user) do %>
    <strong id="followers">
      <%= @user.followers.count %>
    </strong>
    フォロワー
  <% end %>
</div>

app/views/shared/_user-image.html.erb
<%= link_to user_path(attr.user.id) do %>
  <% if attr.user.image.attached? %>
    <%= image_tag(attr.user.image) %>
  <% else %>
    <%= image_tag("default-user.png") %>
  <% end %>
<% end %>

app/views/shared/_user-profile.html.erb
<div class="wrapper_profile">
  <div class="profile-card">
    <div class="profile-card_img">
      <% if user.image.attached? %>
        <%= image_tag(user.image) %>
      <% else %>
        <%= image_tag("default-user.png")%>
      <% end %>
    </div>

    <div class="profile-card_content">
      <%= link_to user_path(user.id) do %>
        <%# -----ユーザー名----- %>
        <div class="profile-card_name"><%= user.username %></div>
      <% end %>

      <%# -----プロフィール編集----- %>
      <% if user_signed_in? && user.id == current_user.id %>
        <div class="profile-card_edit_btn" id="edit-profile" data-toggle="modal" data-target="#edit-profile-modal">
            プロフィールを編集
        </div>
      <% end %>
        <%# -----プロフィール文----- %>
      <div class="profile-card_text">
        <% unless user.profile.nil? %>
          <%= safe_join(user.profile.split("\n"), tag(:br)) %>
        <% end %>
      </div>

      <div class="profile-card-info">
        <%# -----フォロワー数----- %>
        <div class="profile-card-info_item">
          <%= link_to followers_user_path(@user) do %>
            <div id="followers" class="profile-card-info_title"><%= user.followers.count %></div>
            <div class="profile-card-info_text">フォロワー</div>
          <% end %>
        </div>

        <%# -----フォロー数----- %>
        <div class="profile-card-info_item">
          <%= link_to following_user_path(@user) do %>
            <div id="following" class="profile-card-info_title"><%= user.following.count %></div>
            <div class="profile-card-info_text">フォロー</div>
          <% end %>
        </div>

        <%# -----投稿数----- %>
        <div class="profile-card-info_item">
          <div class="profile-card-info_title"><%= user.reviews.count %></div>
          <div class="profile-card-info_text">投稿数</div>
        </div>
      </div>

      <%# -----フォローボタン----- %>
      <% if user_signed_in? && user.id != current_user.id %>
        <div class="profile-card-ctr">
          <%= render 'relationships/follow_form' %>
        </div>
      <% end %>
    </div>

  </div>

</div>
<% if current_user.present? && @user.id == current_user.id %>
  <%= render partial: "users/edit-profile-modal", locals: { user: user } %>
<% end %>